version: '3.8'
services:

  app:
    container_name: dcr-app
    image: dcr-app-image:latest
    ports:
      - 8888:8888
    networks:
      - exa-net

  mongodb:
    container_name: dcr-db
    image: dcr-db-image:latest
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    networks:
      - exa-net

networks:
  exa-net:
    external: true