services:

  app:
    container_name: dgr-app
    image: dgr-app-image:latest
    environment:
      MONGODB_HOST: dgr-db
      MONGODB_USER: admin
      MONGODB_PASS: yellow
      MONGODB_PORT: "27017"
    ports:
      - 8888:8888
    networks:
      - exa-net
    depends_on:
      - mongodb

  mongodb:
    container_name: dgr-db
    image: dgr-db-image:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: yellow
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    networks:
      - exa-net

networks:
  exa-net:
    external: true